language: node_js
node_js:
  - "7"
sudo: required
cache:
  directories:
    - "node_modules"
services:
  - docker
before_deploy:
script:
  - 'sudo apt-get install python3'
  - 'curl -O https://bootstrap.pypa.io/get-pip.py'
  - 'python get-pip.py --user'
  - 'pip install awscli --upgrade --user'
  - 'npm run docker:build && npm run aws:release'
